### ISSUE TITLE
Model doesnt save

### ISSUE THREAD

**Issue by WellImDumb** [001honi/vc-cycle-gan#1]
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./model/A1_to_B\A1_to_B.ckpt

**Comment by 001honi** [comment]
https://drive.google.com/drive/u/2/folders/1ZtDPrft0eurQ80ymgpToS2LZ-0ZW-byz

The models are trained in Colab via this drive folder. You can download missing paths anytime.

**Comment by WellImDumb** [comment]
I want to train my custom model and im not training in colab. After running train.py the model doesnt save. Missing paths? It just doesnt save the checkpoint.

**Comment by 001honi** [comment]
Okay, I see. In the _hyparams.py_ script there is a _check_epoch_ parameter. Give the value 1 for saving the model for each iteration.  Default 1000 is a large value and needs lots of time to first save.
